export const REPORT_CLIENT = 'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee'
export const REPORT_RANGE = { from: '2026-09-01T00:00:00Z', to: '2026-09-03T00:00:00Z', groupBy: 'day' as const, pageSize: 1 }
export const CREDIT_METRICS = `{"grants":10.0000,"consumption":4.0000,"postedConsumption":4.0000,"adjustments":0,"reversals":0,"netActivity":6.0000,"holdsCreated":10,"holdsClosed":10,"holdNetActivity":0,"releasedWithoutConsumption":0,"unusedOnCommit":6,"releases":6,"usagePostingDifference":0,"consumptionToGrantRatio":0.40000000,"ratioStatus":"defined"}`
export function creditFixture(clientId = REPORT_CLIENT, cursor: string | null = 'credit-next', day = '01', asOf = '2026-10-09T14:00:00.123456Z') {
  return `{"schemaVersion":1,"clientId":"${clientId}","unit":"abstract_credits","from":"2026-09-01T00:00:00Z","to":"2026-09-03T00:00:00Z","groupBy":"day","timeZone":"UTC","asOf":"${asOf}","provenance":{"source":"immutable_ledger_and_usage","ledgerDateBasis":"created_at","usageDateBasis":"created_at","membership":"committed_first_page_snapshot","netBasis":"posted_owned_ledger_effects","consumptionBasis":"usage_records","ledgerEntryCount":4,"usageRecordCount":1,"unsettledUsageCount":0,"unsettledUsageCredits":0},"totals":${CREDIT_METRICS},"items":[{"bucketStart":"2026-09-${day}T00:00:00Z","periodStart":"2026-09-${day}T00:00:00Z","periodEnd":"2026-09-${day === '01' ? '02' : '03'}T00:00:00Z","metrics":${CREDIT_METRICS}}],"nextCursor":${JSON.stringify(cursor)}}`
}
export const EXPENSE_METRICS = `{"observationCount":2,"unresolvedCount":0,"estimatedCount":1,"reconciledCount":1,"withoutUsageCount":1,"withInvoiceCount":1,"missingAmountCount":0,"retainedEstimateCount":2,"retainedEstimatedExpense":6.0000,"unreconciledEstimatedExpense":2.0000,"reconciledProviderExpense":3.0000,"effectiveExpense":5.0000,"estimateSources":[{"source":"provider_response","observationCount":2,"amount":6.0000}],"actualSources":[{"source":"manual_reconciliation","observationCount":1,"amount":3.0000}]}`
export function expenseFixture(clientId = REPORT_CLIENT, cursor: string | null = null, provider = 'provider', asOf = '2026-10-09T14:01:00.654321Z') {
  return `{"schemaVersion":1,"clientId":"${clientId}","unit":"provider_money","filters":{"from":"2026-09-01T00:00:00Z","to":"2026-09-03T00:00:00Z","groupBy":"day","pageSize":1,"dimensions":["currency","provider","model","status","source"],"currency":null,"provider":null,"model":null,"status":null,"source":null},"timeZone":"UTC","asOf":"${asOf}","provenance":{"source":"provider_cost_records","accountingDateBasis":"captured_at","membership":"committed_first_page_revisions","sourceGroupingBasis":"actual_else_estimated","observationCount":2,"unknownCurrencyCount":0,"missingAmountCount":0},"totals":[{"currencyCode":"USD","metrics":${EXPENSE_METRICS}}],"items":[{"bucketStart":"2026-09-01T00:00:00Z","periodStart":"2026-09-01T00:00:00Z","periodEnd":"2026-09-02T00:00:00Z","key":{"currencyCode":"USD","provider":${JSON.stringify(provider)},"model":"model","status":"reconciled","source":"manual_reconciliation"},"metrics":${EXPENSE_METRICS}}],"nextCursor":${JSON.stringify(cursor)}}`
}
