import {EXPENSE_METRICS,REPORT_CLIENT} from './billingReportsFixture'
import type {AnomalyFilters} from '../types/billingAnomalies'
export const ANOMALY_ID='019a0000-0000-7000-8000-000000006601',ANOMALY_CONFIG='019a0000-0000-7000-8000-000000006602'
export function anomalyItemFixture(client=REPORT_CLIENT,signal='provider_expense',revision='0',status='open',from='2026-09-01T00:00:00Z',to='2026-09-03T00:00:00Z'){
 const credit=signal==='credit_consumption_to_grants'
 const provenance='{"ledgerEntryCount":1,"usageRecordCount":1,"unsettledUsageCount":0,"unsettledUsageCredits":0,"source":"immutable_ledger_and_usage","ledgerDateBasis":"created_at","usageDateBasis":"created_at","membership":"committed_first_page_snapshot","netBasis":"posted_owned_ledger_effects","consumptionBasis":"usage_records"}'
 return `{"evidence":{"evaluationId":"${ANOMALY_ID}","clientId":"${client}","configVersion":"${ANOMALY_CONFIG}","configHash":"${'a'.repeat(64)}","ruleKey":"fixture-rule","ruleVersion":1,"ownerAlias":"test-operator","signal":"${signal}","units":"${credit?'ratio':'provider_money'}","currency":${credit?'null':'"USD"'},"expenseBasis":${credit?'null':'"effective_expense"'},"comparator":"gte","threshold":1.0000,"scopeOrigin":"client_override","windowFrom":"${from}","windowTo":"${to}","capturedAt":"2026-10-10T00:00:00Z","asOf":"2026-10-10T00:00:00Z","inputs":{"grants":${credit?'1000000000.0000':'null'},"consumption":${credit?'1000000000.0001':'null'},"creditProvenance":${credit?provenance:'null'},"expense":${credit?'null':EXPENSE_METRICS},"unknownCurrencyCount":0,"unknownMissingAmountCount":0,"totalObservationCount":${credit?'0':'2'},"emptyData":false},"decision":{"outcome":"breached","reason":"${credit?'exact_consumption_to_grants':'effective_expense'}","completeness":"complete"},"algorithm":"exact-rational-v1","schemaVersion":1,"sourceDateBasis":"${credit?'created_at':'captured_at'}","membership":"committed_evaluation_snapshot"},"workflow":{"status":"${status}","revision":${revision}},"routing":{"state":"unmapped","displayOwner":null,"version":null,"contentHash":null,"destination":null,"externalDelivery":"not_configured","reloadState":"valid"},"historical":false}`
}
export function anomalyPageFixture(f:AnomalyFilters,client=REPORT_CLIENT){return `{"clientId":"${client}","filters":${JSON.stringify(f)},"asOf":"${new Date().toISOString()}","policy":{"version":"${ANOMALY_CONFIG}","state":"configured"},"items":[${anomalyItemFixture(client,f.signal??'provider_expense','0','open',f.from,f.to)}],"coverageGaps":[],"moreCoverageGaps":false,"nextCursor":null,"canTransition":true}`}
export function anomalyHistoryMetadata(){const asOf=new Date();return {historyAsOf:asOf.toISOString(),historyExpiresAt:new Date(asOf.getTime()+900000).toISOString()}}
export function anomalyDetailFixture(client=REPORT_CLIENT,revision='0',status='open',canTransition=true){
 const states=['open','acknowledged','resolved'];const count=Number(revision)
 const history=Array.from({length:count},(_,n)=>{const r=count-n;return {operationId:`019a0000-0000-7000-8000-${String(r).padStart(12,'0')}`,actorId:client,beforeStatus:states[(r-1)%3],afterStatus:states[r%3],beforeRevision:r-1,revision:r,reason:'fixture reason',at:'2026-10-10T00:00:00Z',correlationId:ANOMALY_CONFIG,routeVersion:null}})
 return `{"item":${anomalyItemFixture(client,'provider_expense',revision,status)},"history":${JSON.stringify(history)},"nextHistoryCursor":null,"canTransition":${canTransition},${JSON.stringify(anomalyHistoryMetadata()).slice(1,-1)}}`
}
