import {useId,useLayoutEffect,useRef,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {useAuth} from '../../../hooks/useAuth'
import {Modal} from '../../shared/Modal'
import {normalizeAnomalyFilters} from '../../../api/billingAnomaliesApi'
import {instantMicros,utcInstant} from '../../../api/billingReportsApi'
import {useAnomalyInvestigation} from '../../../queries/billingAnomalyQueries'
import type {AnomalyEvidence,AnomalyFilters,AnomalyItem} from '../../../types/billingAnomalies'
import type {ReportFilters,ReportKind} from '../../../types/billingReports'
import './anomalies.css'
import {retireAnomalyScopes,hasAnomalyFilterBlock,useAnomalyFilterBlock} from '../../../queries/billingAnomalyKeys'
const title=(kind:ReportKind)=>kind==='expense'?'Expense anomaly signals':'Abstract-credit consumption signals'
function initial(kind:ReportKind,range:ReportFilters):AnomalyFilters {return {from:range.from,to:range.to,signal:kind==='expense'?'provider_expense':'credit_consumption_to_grants',currency:null,configVersion:null,ruleKey:null,ruleVersion:null,outcome:null,workflowStatus:null,owner:null,policy:'current',pageSize:25}}
const label=(value:string)=>value.replace(/_/g,' ')
function Outcome({item}:{item:AnomalyItem}) {const d=item.evidence.decision;return <span>{d.outcome==='breached'?'⚠ Breach observed':d.outcome==='not_evaluable'?'⚠ Not evaluable':'Threshold not crossed'}; {label(d.completeness)} evidence; operator {label(item.workflow.status)}{item.historical?'; historical policy':''}</span>}
function Evidence({e}:{e:AnomalyEvidence}){
 const expense=e.inputs.expense
 return <><dl className="report-metrics">
  {Object.entries({'Client':e.clientId,'Evaluation':e.evaluationId,'Signal':e.signal==='provider_expense'?`Provider expense by currency: ${e.currency}`:'Abstract Soveris credit consumption to grants','Saved threshold':`${e.comparator==='gte'?'≥':'>'} ${e.threshold} ${e.currency??'consumption / grants ratio'}`,'Configuration version':e.configVersion,'Configuration content hash':e.configHash,'Rule and version':`${e.ruleKey} / ${e.ruleVersion}`,'Saved owner alias':e.ownerAlias,'Expense basis':e.expenseBasis??'Not applicable — abstract credits','UTC window':`${e.windowFrom} inclusive → ${e.windowTo} exclusive`,'Captured at (UTC)':e.capturedAt,'Saved inputs as of (UTC)':e.asOf,'Source date basis':e.sourceDateBasis,'Membership':e.membership,'Evaluation outcome':label(e.decision.outcome),'Completeness':label(e.decision.completeness),'Saved decision reason':label(e.decision.reason),'Algorithm':e.algorithm}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}
  {e.signal==='credit_consumption_to_grants'&&<><div><dt>Saved consumption numerator (abstract credits)</dt><dd>{e.inputs.consumption}</dd></div><div><dt>Saved grants denominator (abstract credits)</dt><dd>{e.inputs.grants}</dd></div><div><dt>Exact consumption to grants ratio</dt><dd>{/^0(?:\.0+)?$/.test(e.inputs.grants??'0')?'Not defined — zero grants':`${e.inputs.consumption} / ${e.inputs.grants} (exact; no rounded decision)`}</dd></div></>}
  {expense&&<><div><dt>Effective expense</dt><dd>{expense.effectiveExpense??'Not available'} {e.currency}</dd></div><div><dt>Reconciled provider expense</dt><dd>{expense.reconciledProviderExpense??'Not available'} {e.currency}</dd></div><div><dt>Unreconciled estimated expense</dt><dd>{expense.unreconciledEstimatedExpense??'Not available'} {e.currency}</dd></div><div><dt>Retained historical estimated expense</dt><dd>{expense.retainedEstimatedExpense??'Not available'} {e.currency}</dd></div>{(['observationCount','unresolvedCount','estimatedCount','reconciledCount','withoutUsageCount','withInvoiceCount','missingAmountCount','retainedEstimateCount'] as const).map(k=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1')}</dt><dd>{expense[k]}</dd></div>)}</>}
  <div><dt>Unknown currency observations</dt><dd>{e.inputs.unknownCurrencyCount}</dd></div><div><dt>Unknown currency missing amounts</dt><dd>{e.inputs.unknownMissingAmountCount}</dd></div><div><dt>Total observations</dt><dd>{e.inputs.totalObservationCount}</dd></div><div><dt>Empty source data</dt><dd>{e.inputs.emptyData?'Yes':'No'}</dd></div>
  {e.inputs.creditProvenance&&Object.entries(e.inputs.creditProvenance).map(([k,v])=><div key={k}><dt>Credit provenance: {k.replace(/([A-Z])/g,' $1')}</dt><dd>{v}</dd></div>)}
 </dl>{expense&&<><h5 className="font-semibold">Saved expense source composition</h5><ul>{[...expense.estimateSources.map(s=>({...s,kind:'Retained estimate'})),...expense.actualSources.map(s=>({...s,kind:'Reconciled actual'}))].map(s=><li key={s.kind+s.source}>{s.kind}: {label(s.source)}, {s.observationCount} observations, {s.amount} {e.currency}</li>)}</ul>{e.expenseBasis==='reconciled_provider_expense'&&<p>Estimated observations are excluded from this rule’s amount and can leave partial evidence.</p>}</>}
 {e.decision.completeness==='partial'&&<p>⚠ Incomplete evidence. A partial breach remains a breach; a partial non-crossing result does not establish healthy expense.</p>}
 <p>Saved evidence is immutable. A live report can differ from this evaluation’s source snapshot. No per-job membership is inferred.</p><Link to={`/billing/clients/${e.clientId}/reports`}>Open authorized live reports for this Client</Link>
 </>
}
function Routing({item}:{item:AnomalyItem}){const r=item.routing;return <><p>Saved owner alias: {item.evidence.ownerAlias}. Routing: {r.state==='mapped'?r.displayOwner:r.state==='unavailable'?'Owner routing unavailable':'Owner routing not configured'}.</p>{r.destination&&<Link to={r.destination}>Investigate with {r.displayOwner}</Link>}{r.version&&<p>Route descriptor version: {r.version}; content: {r.contentHash}</p>}{r.reloadState==='last_known_good'&&<p>⚠ Owner mapping reload failed; the previous complete descriptor remains active.</p>}<p>External delivery: not configured. No external message is sent.</p></>}
function AnomalyFilterForm({kind,filters,onApply,blocked}:{kind:ReportKind;filters:AnomalyFilters;blocked:boolean;onApply:(f:AnomalyFilters)=>void}){
 const prefix=useId();const [draft,setDraft]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(filters).map(([k,v])=>[k,String(v??'')])));const [errors,setErrors]=useState<Record<string,string>>({});const summary=useRef<HTMLDivElement>(null)
 const change=(key:string,value:string)=>setDraft({...draft,[key]:value})
 const text=(key:string,name:string)=><label key={key} htmlFor={`${prefix}-${key}`}>{name}<input id={`${prefix}-${key}`} value={draft[key]} onChange={e=>change(key,e.target.value)} aria-invalid={Boolean(errors[key])} aria-describedby={errors[key]?`${prefix}-${key}-error`:undefined}/>{errors[key]&&<span id={`${prefix}-${key}-error`}>{errors[key]}</span>}</label>
 const select=(key:string,name:string,options:[string,string][])=> <label key={key} htmlFor={`${prefix}-${key}`}>{name}<select id={`${prefix}-${key}`} value={draft[key]} onChange={e=>change(key,e.target.value)}>{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 return <form className="report-filters anomaly-filters" aria-label={`${title(kind)} filters`} onSubmit={e=>{
  e.preventDefault();if(blocked)return;const next:Record<string,string>={};for(const key of ['from','to'])try{utcInstant(draft[key])}catch{next[key]='Use a valid timestamp with timezone.'}
  if(!next.from&&!next.to&&(instantMicros(draft.to)<=instantMicros(draft.from)||instantMicros(draft.to)-instantMicros(draft.from)>366n*86400000000n))next.to='Use an increasing range of at most 366 days.'
  if(kind==='expense'&&draft.currency&&!/^[A-Z]{3}$/.test(draft.currency))next.currency='Use an exact three-letter uppercase currency.'
  for(const key of ['owner','ruleKey'])if(draft[key]&&!/^[a-z][a-z0-9._-]{0,63}$/.test(draft[key]))next[key]='Use a safe alias, up to 64 characters.'
  if(draft.configVersion&&!/^[\da-f]{8}-[\da-f]{4}-7[\da-f]{3}-[89ab][\da-f]{3}-[\da-f]{12}$/.test(draft.configVersion))next.configVersion='Use an exact UUIDv7 configuration version.'
  if(!/^([1-9]\d{0,2})$/.test(draft.pageSize)||Number(draft.pageSize)>100)next.pageSize='Use 1–100 evaluations per page.'
  if(draft.ruleVersion&&(!/^[1-9]\d*$/.test(draft.ruleVersion)||Number(draft.ruleVersion)>2147483647))next.ruleVersion='Use a positive rule version.'
  if(Object.keys(next).length){setErrors(next);requestAnimationFrame(()=>summary.current?.focus());return}
  const f=normalizeAnomalyFilters({...filters,from:draft.from,to:draft.to,currency:kind==='expense'?draft.currency||null:null,owner:draft.owner||null,ruleKey:draft.ruleKey||null,configVersion:draft.configVersion||null,ruleVersion:draft.ruleVersion?Number(draft.ruleVersion):null,pageSize:Number(draft.pageSize),policy:draft.policy as AnomalyFilters['policy'],outcome:draft.outcome as AnomalyFilters['outcome']||null,workflowStatus:draft.workflowStatus as AnomalyFilters['workflowStatus']||null});setErrors({});onApply(f)
 }}>
  <h4>Filter saved {kind==='expense'?'expense':'abstract-credit'} evaluations</h4>
  {Object.keys(errors).length>0&&<div ref={summary} tabIndex={-1} role="alert"><p>Correct anomaly filters</p><ul>{Object.entries(errors).map(([key,error])=><li key={key}><a href={`#${prefix}-${key}`} onClick={event=>{event.preventDefault();document.getElementById(`${prefix}-${key}`)?.focus()}}>{error}</a></li>)}</ul></div>}
  <div className="anomaly-filter-grid">{text('from','Anomaly window start (inclusive UTC)')}{text('to','Anomaly window end (exclusive UTC)')}{kind==='expense'&&text('currency','Anomaly currency (exact)')}
  {select('policy','Anomaly policy',[['current','Current accepted policy'],['historical','Historical policies'],['all','All policies']])}
  {select('outcome','Evaluation outcome',[['','All outcomes (including incomplete)'],['breached','Breaches only'],['not_breached','Threshold not crossed'],['not_evaluable','Not evaluable']])}
  {select('workflowStatus','Operator status',[['','All operator statuses'],['open','Open'],['acknowledged','Acknowledged'],['resolved','Resolved investigation'],['not_applicable','Not applicable']])}
  {text('owner','Saved owner alias filter')}{text('configVersion','Configuration version filter')}{text('ruleKey','Rule key filter')}{text('ruleVersion','Rule version filter')}{text('pageSize','Evaluations per page')}</div>
  <button type="submit" aria-disabled={blocked}>Apply anomaly filters</button>{blocked&&<p role="status">Wait for the rate limit to end or confirm/recover the pending operator operation before applying filters.</p>}<p>Coverage warnings are shown independently of outcome filters.</p>
 </form>
}
function Results({client,filters,kind,authority,deny}:{client:string;filters:AnomalyFilters;kind:ReportKind;authority:()=>string;deny:(status:number)=>void}){
 const lane=useAnomalyInvestigation(client,filters,authority,deny);const c=lane.controller;const {evaluationId}=useParams();const auth=useAuth();const canAct=auth.hasPermission('billing:reconcile')&&lane.detail?.canTransition===true
 const [view,setView]=useState('auto');const sectionHeading=useRef<HTMLHeadingElement>(null);const refreshEvidence=useRef<HTMLButtonElement>(null);const reasonInput=useRef<HTMLTextAreaElement>(null);const errorSummary=useRef<HTMLDivElement>(null);const reasonId=useId(),descriptionId=useId();const continuation=useRef<HTMLButtonElement>(null)
 useLayoutEffect(()=>{if(evaluationId)void c.select(evaluationId)},[c,evaluationId])
 useLayoutEffect(()=>{if(lane.commandState==='invalid')errorSummary.current?.focus()},[lane.commandState])
 useLayoutEffect(()=>{if(document.activeElement===continuation.current&&(lane.stale||lane.page&&!lane.page.nextCursor))sectionHeading.current?.focus()},[lane.stale,lane.page])
 if(lane.retired)return null
 const detail=lane.detail?.item.evidence.signal===filters.signal?lane.detail:null
 const actions=detail?.item.workflow.status==='open'?['acknowledged'] as const:detail?.item.workflow.status==='acknowledged'?['resolved','open'] as const:detail?.item.workflow.status==='resolved'?['open'] as const:[]
 const row=(i:AnomalyItem)=><><Outcome item={i}/><p>{i.evidence.windowFrom} → {i.evidence.windowTo} UTC; {i.evidence.currency??'abstract Soveris credits'}</p><p>Threshold {i.evidence.comparator==='gte'?'≥':'>'} {i.evidence.threshold} {i.evidence.currency??'ratio'}; owner {i.evidence.ownerAlias}; version {i.evidence.ruleVersion}</p><button type="button" aria-disabled={lane.commandBusy||lane.commandState==='ambiguous'||lane.retryAt>Date.now()} onClick={()=>{if(!lane.commandBusy&&lane.commandState!=='ambiguous'&&lane.retryAt<=Date.now())void c.select(i.evidence.evaluationId)}}>Inspect evaluation {i.evidence.evaluationId}</button></>
 return <div className="anomaly-results">
  <h4 ref={sectionHeading} tabIndex={-1}>Saved evaluations and coverage</h4>
  <button type="button" aria-disabled={lane.listBusy||lane.retryAt>Date.now()} onClick={()=>{if(!lane.listBusy)void c.refresh()}}>Refresh anomaly signals</button>
  <p role="status" aria-label={`${title(kind)} status`}>{lane.listBusy?'Loading saved anomaly evidence…':lane.message}</p>
  {lane.error&&<p role="status">{lane.error} Use Refresh anomaly signals to retry when available.</p>}{lane.retryAt>Date.now()&&<p role="status">Rate limited. Wait before retrying.</p>}
  {lane.stale&&<p role="status">Anomaly list snapshot is stale. Refresh anomaly signals before continuing.</p>}
  {lane.page&&<><p>Accepted policy: {label(lane.page.policy.state)}; version {lane.page.policy.version??'not configured'}. Query as of {lane.page.asOf} UTC.</p>
   {lane.page.coverageGaps.length>0&&<div role="status"><p>⚠ Missing evaluation coverage: {lane.page.coverageGaps.length} visible segments{lane.page.moreCoverageGaps?'; further coverage gaps exist':''}. These are separate from saved outcomes.</p><ul>{lane.page.coverageGaps.map(g=><li key={g.gapId+g.windowFrom}>{g.windowFrom} → {g.windowTo} UTC; retired policy {g.retiredVersion}</li>)}</ul></div>}
   {lane.page.items.length===0?<p>{lane.page.policy.state==='configured'?'No saved evaluations match this window and these filters. This is not a healthy assessment.':`Policy ${label(lane.page.policy.state)}. Historical evidence remains available through the policy filter.`}</p>:<div className={`report-data report-view-${view}`}><label>{title(kind)} data view <select value={view} onChange={e=>setView(e.target.value)}><option value="auto">Responsive</option><option value="table">Table</option><option value="structured">Structured list</option></select></label>
   <div className="report-table-view report-table-scroll" role="region" aria-label={`${title(kind)} table scroll`} tabIndex={0}><table><caption>{title(kind)} — saved evaluations</caption><thead><tr><th scope="col">UTC window and evidence</th><th scope="col">Owner routing</th></tr></thead><tbody>{lane.page.items.map(i=><tr key={i.evidence.evaluationId}><th scope="row">{row(i)}</th><td><Routing item={i}/></td></tr>)}</tbody></table></div>
   <ol className="report-structured-view report-records">{lane.page.items.map(i=><li key={i.evidence.evaluationId}>{row(i)}<Routing item={i}/></li>)}</ol></div>}
   <button ref={continuation} type="button" aria-disabled={!lane.page.nextCursor||lane.listBusy||lane.stale||lane.retryAt>Date.now()} onClick={()=>void c.more()}>Load more anomaly evaluations</button><p>{lane.page.nextCursor?'More evaluations available.':'End of saved evaluation results.'}</p>
  </>}
  {lane.detailBusy&&<p role="status">Loading saved evidence and operator history…</p>}{lane.detailError&&<p role="status">{lane.detailError}</p>}
  {detail&&<section aria-label="Anomaly investigation evidence" className="report-currency"><h4>Investigation evidence</h4><Outcome item={detail.item}/><Evidence e={detail.item.evidence}/><Routing item={detail.item}/>
   <p>Current operator status: {label(detail.item.workflow.status)}; revision {detail.item.workflow.revision}. Resolved means investigation closed; saved expense is not corrected or cleared.</p>
   <button ref={refreshEvidence} type="button" aria-disabled={lane.detailBusy||lane.commandBusy||lane.commandState==='ambiguous'||lane.retryAt>Date.now()} onClick={()=>void c.refreshDetail()}>Refresh investigation evidence</button>
   {canAct?actions.map(action=><button key={action} type="button" aria-disabled={lane.commandBusy||lane.detailBusy||lane.commandState==='ambiguous'} onClick={()=>c.openAction(action)}>{action==='acknowledged'?'Acknowledge anomaly':action==='resolved'?'Resolve investigation':'Reopen investigation'}</button>):<p>Investigation is read-only. Operator actions require billing:reconcile.</p>}
   <h5>Operator history</h5><p>History snapshot as of {detail.historyAsOf} UTC; expires at {detail.historyExpiresAt} UTC.</p>{lane.historyStale&&<p role="status">Operator history snapshot is stale. Refresh investigation evidence before continuing history.</p>}<ol className="report-records">{detail.history.map(t=><li key={t.operationId}>{label(t.beforeStatus)} → {label(t.afterStatus)}; revision {t.revision}; actor {t.actorId}; {t.at} UTC; operation {t.operationId}{t.reason&&<p>Operator reason: {t.reason}</p>}{t.routeVersion&&<p>Route version: {t.routeVersion}</p>}</li>)}</ol>{detail.history.length===0&&<p>No operator transitions recorded.</p>}
   <button type="button" aria-disabled={!detail.nextHistoryCursor||lane.detailBusy||lane.commandBusy||lane.historyStale||lane.retryAt>Date.now()} onClick={()=>void c.moreHistory()}>Load more operator history</button><p>{detail.nextHistoryCursor?'More operator history available.':'End of operator history.'}</p>
  </section>}
  {lane.receipt&&<p role="status">Confirmed operation {lane.receipt.operationId}: {label(lane.receipt.status)}, revision {lane.receipt.revision}. Recorded at {lane.receipt.at} UTC.</p>}
  {lane.commandState==='ambiguous'&&<div role="status"><p>Outcome not yet confirmed. Operation {lane.command?.operationId} is retained while this authority remains valid.</p><button type="button" aria-disabled={lane.commandBusy||lane.retryAt>Date.now()} onClick={()=>void c.recover()}>Recover same operation</button></div>}
  <Modal isOpen={Boolean(lane.action&&detail&&canAct)} onClose={c.closeAction} title="Confirm anomaly operator status" descriptionId={descriptionId} initialFocusRef={reasonInput} returnFocusRef={refreshEvidence} closeDisabled={lane.commandBusy}>
   <div className="anomaly-confirmation"><p id={descriptionId}>Client {client}. Evaluation {detail?.item.evidence.evaluationId}; UTC window {detail?.item.evidence.windowFrom} → {detail?.item.evidence.windowTo}. Current operator status {detail?.item.workflow.status}, revision {detail?.item.workflow.revision}; proposed status {lane.action}. Saved expense, credits and evaluation outcome remain unchanged.</p>
   {lane.commandState==='invalid'&&<div ref={errorSummary} tabIndex={-1} role="alert"><p>Correct the operator request</p><a href={`#${reasonId}`} onClick={event=>{event.preventDefault();reasonInput.current?.focus()}}>{lane.message}</a></div>}
   <label htmlFor={reasonId}>Operator reason{lane.action!=='acknowledged'?' (required)':' (optional)'}</label><textarea ref={reasonInput} id={reasonId} value={lane.reason} required={lane.action!=='acknowledged'} maxLength={2000} aria-invalid={lane.commandState==='invalid'} aria-describedby={`${reasonId}-help`} readOnly={lane.commandBusy||lane.commandState==='ambiguous'} onChange={e=>c.setReason(e.target.value)}/><p id={`${reasonId}-help`}>Resolve and reopen require 1–1000 Unicode characters after trimming. Reason is private operator content.</p>
   <p role="status">{lane.commandBusy?'Confirming operator status…':lane.commandState==='ambiguous'?'Outcome not yet confirmed. Recover with the same operation.':lane.commandState==='conflict'?lane.message:''}</p>
   <button type="button" aria-disabled={lane.commandBusy||lane.commandState==='ambiguous'||lane.commandState==='conflict'||lane.retryAt>Date.now()} onClick={()=>void c.confirm()}>Confirm operator status</button><button type="button" aria-disabled={lane.commandBusy} onClick={c.closeAction}>Cancel confirmation</button>
   {lane.commandState==='ambiguous'&&<button type="button" aria-disabled={lane.commandBusy||lane.retryAt>Date.now()} onClick={()=>void c.recover()}>Recover same operation</button>}
   </div>
  </Modal>
 </div>
}
export function AnomalyPanel({client,kind,range,authority,deny}:{client:string;kind:ReportKind;range:ReportFilters;authority:()=>string;deny:(status:number)=>void}){
 const [filters,setFilters]=useState(()=>initial(kind,range));const blocked=useAnomalyFilterBlock(client);return <section className="anomaly-panel" aria-label={title(kind)}><h3>{title(kind)}</h3><p>Immutable saved evaluations, independent of this live report. Outcome, completeness, operator status and routing are separate.</p><AnomalyFilterForm kind={kind} filters={filters} blocked={blocked} onApply={f=>{if(hasAnomalyFilterBlock(client))return;if(JSON.stringify(f)!==JSON.stringify(filters)){retireAnomalyScopes(client,filters.signal);setFilters(f)}}}/><Results key={JSON.stringify(filters)} client={client} filters={filters} kind={kind} authority={authority} deny={deny}/></section>
}
