import { LoadedRows } from './LoadedRows'
import { CREDIT_FIELDS, EXPENSE_AMOUNTS, EXPENSE_COUNTS, type CreditField, type CreditMetrics, type CreditPage, type ExpenseBucket, type ExpenseMetrics, type ExpensePage } from '../../../types/billingReports'
import { CreditValue, DataViews, MetricList, MetricTable, Money, PeriodLabel, ScrollTable, creditLabels, type MetricRow } from './ReportPresentation'
const mainFields:CreditField[]=['grants','consumption','postedConsumption','releases','adjustments','reversals','netActivity']
const holdFields=CREDIT_FIELDS.filter(k=>!mainFields.includes(k))
function creditRows(metrics:CreditMetrics):MetricRow[] {return [...CREDIT_FIELDS.map(k=>({label:creditLabels[k],value:<CreditValue value={metrics[k]}/> })),{label:creditLabels.consumptionToGrantRatio,value:<CreditValue value={metrics.consumptionToGrantRatio} ratio/>},{label:creditLabels.ratioStatus,value:metrics.ratioStatus==='defined'?'Defined (unitless)':'Not defined — no grants in this period'}]}
function CreditPeriodTable({page,holds=false}:{page:CreditPage;holds?:boolean}) {
  const fields=holds?holdFields:mainFields
  const title=holds?'Credit holds and posting by UTC period':'Credit activity by UTC period'
  return <ScrollTable label={`${title} scrollable data`}><table><caption>{title} — Client {page.clientId}, {page.from} inclusive to {page.to} exclusive; abstract Soveris credits</caption><thead><tr><th scope="col">UTC period</th>{fields.map(k=><th key={k} scope="col">{creditLabels[k]}</th>)}{!holds&&<th scope="col">Consumption-to-grant ratio</th>}</tr></thead><tbody>{page.items.map(i=><tr key={i.bucketStart}><th scope="row"><PeriodLabel period={i}/></th>{fields.map(k=><td key={k}><CreditValue value={i.metrics[k]}/></td>)}{!holds&&<td><CreditValue value={i.metrics.consumptionToGrantRatio} ratio/></td>}</tr>)}</tbody></table></ScrollTable>
}
export function CreditActivityResults({page}:{page:CreditPage}) {
  const totals=creditRows(page.totals),empty=page.provenance.ledgerEntryCount==='0'&&page.provenance.usageRecordCount==='0'
  return <div className="space-y-4"><p>All credit amounts are abstract Soveris credits. The consumption-to-grant ratio is unitless.</p>
    {empty&&<p role="status" className="state-indicator">No recorded credit activity in this period. Dense zero periods remain available; this does not establish whether a wallet is configured.</p>}
    {page.provenance.unsettledUsageCount!=='0'&&<p className="state-indicator">Incomplete evidence: {page.provenance.unsettledUsageCount} usage records, <CreditValue value={page.provenance.unsettledUsageCredits}/>, await a matching financial tail at this snapshot.</p>}
    <h3 className="text-lg font-semibold">Full-window credit totals</h3><DataViews label="Credit totals" table={<MetricTable caption={`Full-window abstract-credit totals — Client ${page.clientId}, ${page.from} to ${page.to} (exclusive)`} rows={totals}/>} structured={<MetricList rows={totals}/>}/>
    <details><summary>Credit definitions</summary><p>Net activity = grants − posted consumption + adjustments + reversals. It is period owned-credit movement, not current balance.</p><p>Grants are positive subscription grants and promotions. Consumption comes from usage records; posted consumption comes from immutable debits. Releases = released without consumption + unused on commit; they return availability and do not add to grants or net activity.</p><p>Hold net activity = holds created − holds closed: operational movement, not current reserved balance. Usage posting difference = consumption − posted consumption; different accounting periods or pending posting can explain it.</p><p>Consumption-to-grant ratio = full-window consumption / grants, rounded by the server to eight places. No grants means not defined; carried funding can give a ratio above one. Bucket ratios are never averaged.</p></details>
    <LoadedRows items={page.items} unit="periods">{visible=><DataViews label="Credit periods" table={<><CreditPeriodTable page={{...page,items:visible}}/><details><summary>Hold movements and posting details by period</summary><CreditPeriodTable page={{...page,items:visible}} holds/></details></>} structured={<ol className="report-records">{visible.map(i=><li key={i.bucketStart}><details><summary><PeriodLabel period={i}/></summary><MetricList rows={creditRows(i.metrics)}/></details></li>)}</ol>}/>}</LoadedRows>
  </div>
}
const expenseLabels:Record<typeof EXPENSE_AMOUNTS[number]|typeof EXPENSE_COUNTS[number],string>={observationCount:'Observations',unresolvedCount:'Unresolved observations',estimatedCount:'Estimated observations',reconciledCount:'Reconciled observations',withoutUsageCount:'Observations without usage link',withInvoiceCount:'Observations with invoice evidence',missingAmountCount:'Missing effective amounts',retainedEstimateCount:'Retained estimates',retainedEstimatedExpense:'Retained estimated expense (audit context)',unreconciledEstimatedExpense:'Unreconciled estimated expense',reconciledProviderExpense:'Actual/reconciled expense',effectiveExpense:'Effective expense (actual + unreconciled estimates)'}
function expenseRows(m:ExpenseMetrics,currency:string|null):MetricRow[] {return [...EXPENSE_AMOUNTS.map(k=>({label:expenseLabels[k],value:<Money value={m[k]} currency={currency}/> })),...EXPENSE_COUNTS.map(k=>({label:expenseLabels[k],value:m[k]}))]}
function Sources({metrics,currency}:{metrics:ExpenseMetrics;currency:string|null}) {return <div>{(['estimateSources','actualSources'] as const).map(k=><div key={k}><h4 className="font-semibold">{k==='estimateSources'?'Estimate sources (retained evidence)':'Actual sources'}</h4>{metrics[k].length?<ul>{metrics[k].map(s=><li key={s.source}>{s.source.replace(/_/g,' ')}: {s.observationCount} observations; <Money value={s.amount} currency={currency}/></li>)}</ul>:<p>No contributing source evidence.</p>}</div>)}</div>}
function GroupKeys({item,page}:{item:ExpenseBucket;page:ExpensePage}) {return <MetricList rows={(['provider','model','status','source'] as const).map(k=>({label:k,value:!page.filters.dimensions.includes(k)?'Not grouped':item.key[k]??'Unknown'}))}/>}
export function ProviderExpenseResults({page}:{page:ExpensePage}) {
  return <div className="space-y-4"><p>Provider money stays in its original currency. Each currency total covers the full filtered window.</p>
    {page.totals.length===0&&<p role="status" className="state-indicator">No recorded provider-cost observations match these filters. No observations does not confirm free provider execution.</p>}
    {page.provenance.missingAmountCount!=='0'&&<p className="state-indicator">Incomplete evidence: {page.provenance.missingAmountCount} observations have no effective amount; {page.provenance.unknownCurrencyCount} have unknown currency. Known subtotals do not include these amounts.</p>}
    <h3 className="text-lg font-semibold">Full-window expense totals</h3>
    <div className="grid min-w-0 gap-4 xl:grid-cols-2">{page.totals.map(t=><div key={t.currencyCode??'unknown'} className="report-currency state-indicator"><h4 className="font-semibold">{t.currencyCode??'Unknown currency'}</h4><DataViews label={`${t.currencyCode??'Unknown currency'} totals`} table={<MetricTable caption={`Full-window provider expense — ${t.currencyCode??'unknown currency'}, Client ${page.clientId}, ${page.filters.from} to ${page.filters.to} (exclusive)`} rows={expenseRows(t.metrics,t.currencyCode)}/>} structured={<MetricList rows={expenseRows(t.metrics,t.currencyCode)}/>}/><Sources metrics={t.metrics} currency={t.currencyCode}/></div>)}</div>
    <details><summary>Provider expense definitions</summary><p>Effective expense contains one actual amount for each reconciled observation plus unreconciled estimates, within one currency. Retained estimates include superseded estimates and remain audit context; they are excluded from additive effective expense when an actual amount supersedes them.</p><p>Unresolved, estimated and reconciled are the cost statuses. Actual is evidence on a reconciled observation. Reconciled does not necessarily mean paid, invoiced or manually reviewed. A measured zero is known money; Not available means no contributing amount.</p><p>Counts describe persisted cost observations, not every provider attempt or invoice. An optional usage link does not control expense eligibility. Estimate and actual source breakdowns are separate and remain associated with their currency.</p></details>
    <LoadedRows items={page.items} unit="groups">{visible=><DataViews label="Expense groups" table={<ScrollTable label="Provider expense groups scrollable data"><table><caption>Provider expense groups by UTC period and original currency — Client {page.clientId}, {page.filters.from} to {page.filters.to} (exclusive)</caption><thead><tr><th scope="col">UTC period</th><th scope="col">Currency</th><th scope="col">Grouped dimensions</th><th scope="col">Effective expense</th><th scope="col">Evidence details</th></tr></thead><tbody>{visible.map(i=><tr key={JSON.stringify([i.bucketStart,i.key])}><th scope="row"><PeriodLabel period={i}/></th><td>{i.key.currencyCode??'Unknown currency'}</td><td><GroupKeys item={i} page={page}/></td><td><Money value={i.metrics.effectiveExpense} currency={i.key.currencyCode}/></td><td><details><summary>Amounts, counts and source evidence</summary><MetricList rows={expenseRows(i.metrics,i.key.currencyCode)}/><Sources metrics={i.metrics} currency={i.key.currencyCode}/></details></td></tr>)}</tbody></table></ScrollTable>} structured={<ol className="report-records">{visible.map(i=><li key={JSON.stringify([i.bucketStart,i.key])}><details><summary><PeriodLabel period={i}/>{i.key.currencyCode??'Unknown currency'} — <Money value={i.metrics.effectiveExpense} currency={i.key.currencyCode}/></summary><GroupKeys item={i} page={page}/><MetricList rows={expenseRows(i.metrics,i.key.currencyCode)}/><Sources metrics={i.metrics} currency={i.key.currencyCode}/></details></li>)}</ol>}/>}</LoadedRows>
  </div>
}
