import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import {writeFile} from 'node:fs/promises'
import {installSession,mockReports,reportsPath} from './reportMocks'
import {installAnomalies} from './anomalyMocks'
import {ANOMALY_ID} from '../src/test/billingAnomaliesFixture'
test.beforeEach(async({page})=>{await installSession(page);await mockReports().install(page)})
test('keyboard confirms acknowledgement, resolves and reopens while immutable evidence remains',async({page})=>{
 const mock=await installAnomalies(page,{ambiguous:true});await page.goto(reportsPath());const expense=page.getByRole('region',{name:'Expense anomaly signals',exact:true});await expense.getByRole('button',{name:`Inspect evaluation ${ANOMALY_ID}`,exact:true}).focus();await page.keyboard.press('Enter');await expect(expense.getByRole('heading',{name:'Investigation evidence'})).toBeVisible();await expense.getByRole('button',{name:'Acknowledge anomaly'}).focus();await page.keyboard.press('Enter');let dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Operator reason (optional)')).toBeFocused();await expect(dialog).toContainText('proposed status acknowledged');await dialog.getByRole('button',{name:'Confirm operator status'}).focus();await page.keyboard.press('Enter');await expect(dialog.getByRole('button',{name:'Recover same operation'})).toBeVisible();await dialog.getByRole('button',{name:'Recover same operation'}).focus();await page.keyboard.press('Enter');await expect(dialog).not.toBeVisible();await expect(expense.getByRole('button',{name:'Refresh investigation evidence'})).toBeFocused();await expect(expense.getByText(/Confirmed operation/)).toBeVisible();expect(mock.receipts.size).toBe(1)
 await expense.getByRole('button',{name:'Resolve investigation'}).click();dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Confirm operator status'}).click();await expect(dialog.getByRole('alert')).toBeFocused();await dialog.getByRole('alert').getByRole('link').click();await expect(dialog.getByLabel('Operator reason (required)')).toBeFocused();await dialog.getByLabel('Operator reason (required)').fill('Local investigation complete');await dialog.getByRole('button',{name:'Confirm operator status'}).click();await expect(dialog).not.toBeVisible();await expense.getByRole('button',{name:'Reopen investigation'}).click();await page.getByRole('dialog').getByLabel('Operator reason (required)').fill('Recheck local evidence');await page.getByRole('dialog').getByRole('button',{name:'Confirm operator status'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();expect(mock.receipts.size).toBe(3);await expect(expense.getByText('5.0000 USD',{exact:true})).toBeVisible();await expect(expense.getByText(/Current operator status: open; revision 3/)).toBeVisible()
})
test('axe, structured 320-pixel data, text spacing, forced colours and reduced motion',async({page})=>{
 await installAnomalies(page);await page.goto(reportsPath());const expense=page.getByRole('region',{name:'Expense anomaly signals',exact:true});await expense.getByRole('button',{name:`Inspect evaluation ${ANOMALY_ID}`}).click();await expect(expense.getByRole('heading',{name:'Investigation evidence'})).toBeVisible();expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze()).violations).toEqual([])
 await expense.getByRole('button',{name:'Acknowledge anomaly'}).click();expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze()).violations).toEqual([]);await page.keyboard.press('Escape');await page.setViewportSize({width:320,height:700});await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});await page.addStyleTag({content:'*{line-height:1.5!important;letter-spacing:.12em!important;word-spacing:.16em!important}p{margin-bottom:2em!important}'});await expect(expense.getByRole('table')).not.toBeVisible();await expect(expense.locator('.report-structured-view').getByRole('button',{name:`Inspect evaluation ${ANOMALY_ID}`})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('server view-only capability keeps investigation available without operator controls',async({page})=>{
 await installAnomalies(page,{viewOnly:true});await page.goto(reportsPath());const expense=page.getByRole('region',{name:'Expense anomaly signals',exact:true});await expense.getByRole('button',{name:`Inspect evaluation ${ANOMALY_ID}`}).click();await expect(expense.getByText(/Investigation is read-only/)).toBeVisible();await expect(expense.getByRole('button',{name:'Acknowledge anomaly'})).toHaveCount(0)
})
test('local feedback and pending indication meet the declared laptop-browser budgets',async({page},info)=>{
 await installAnomalies(page);await page.goto(reportsPath());const expense=page.getByRole('region',{name:'Expense anomaly signals',exact:true});await expense.getByRole('button',{name:`Inspect evaluation ${ANOMALY_ID}`}).click();await expect(expense.getByRole('button',{name:'Acknowledge anomaly'})).toBeVisible();const samples:number[]=[]
 for(let n=0;n<20;n++){
  const value=await page.evaluate(()=>new Promise<number>(resolve=>{const start=performance.now();const observer=new MutationObserver(()=>{if(document.querySelector('[role=dialog]')){observer.disconnect();resolve(performance.now()-start)}});observer.observe(document.body,{childList:true,subtree:true});[...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent==='Acknowledge anomaly')!.click()}));samples.push(value);await page.getByRole('dialog').getByRole('button',{name:'Cancel confirmation'}).click()
 }
 const p95=[...samples].sort((a,b)=>a-b)[Math.ceil(samples.length*.95)-1];expect(p95).toBeLessThanOrEqual(100)
 let release:()=>void=()=>{};await page.route('**/api/billing/anomalies/*/transitions**',async route=>{await new Promise<void>(resolve=>{release=resolve});await route.abort('timedout')});await expense.getByRole('button',{name:'Acknowledge anomaly'}).click();const pending=await page.evaluate(()=>new Promise<number>(resolve=>{const start=performance.now();const observer=new MutationObserver(()=>{if([...document.querySelectorAll('[role=dialog] [role=status]')].some(s=>s.textContent==='Confirming operator status…')){observer.disconnect();resolve(performance.now()-start)}});observer.observe(document.body,{childList:true,subtree:true,characterData:true});[...document.querySelectorAll<HTMLButtonElement>('[role=dialog] button')].find(b=>b.textContent==='Confirm operator status')!.click()}));expect(pending).toBeLessThanOrEqual(500);release();await expect(page.getByRole('dialog').getByRole('button',{name:'Recover same operation'})).toBeVisible();await writeFile(info.outputPath('feedback-profile.json'),JSON.stringify({profile:'Local Chromium on execution host; 20 dialog openings and one held command response. Not production workload approval.',samplesMilliseconds:samples,p95Milliseconds:p95,pendingMilliseconds:pending,pass:true},null,2))
})

test('ordinary anomaly and report filters preserve recovery identity until the outcome is confirmed',async({page})=>{
 const mock=await installAnomalies(page,{ambiguous:true});await page.goto(reportsPath());const expense=page.getByRole('region',{name:'Expense anomaly signals',exact:true});await expense.getByRole('button',{name:`Inspect evaluation ${ANOMALY_ID}`}).click();await expense.getByRole('button',{name:'Acknowledge anomaly'}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirm operator status'}).click();await expect(page.getByRole('dialog').getByRole('button',{name:'Recover same operation'})).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Cancel confirmation'}).click()
 const operation=[...mock.receipts.keys()][0];await expense.getByLabel('Anomaly currency (exact)').fill('EUR');await expect(expense.getByRole('button',{name:'Apply anomaly filters'})).toHaveAttribute('aria-disabled','true');await expense.getByRole('button',{name:'Apply anomaly filters'}).click({force:true});const report=page.getByRole('form',{name:'Report filters'});await report.getByLabel('Provider (exact match)').fill('unapplied draft');for(const name of ['Apply filters','Reset filters']){await expect(report.getByRole('button',{name})).toHaveAttribute('aria-disabled','true');await report.getByRole('button',{name}).click({force:true})}
 await expect(report.getByLabel('Provider (exact match)')).toHaveValue('unapplied draft');await expect(expense.getByRole('heading',{name:'Investigation evidence'})).toBeVisible();await expense.getByRole('button',{name:'Recover same operation'}).click();await expect(expense.getByText(new RegExp(`Confirmed operation ${operation}`))).toBeVisible();expect([...mock.receipts.keys()]).toEqual([operation]);await expect(report.getByRole('button',{name:'Apply filters'})).toHaveAttribute('aria-disabled','false')
})
