import {test,expect} from '@playwright/test'
import {readFile,writeFile} from 'node:fs/promises'
import AxeBuilder from '@axe-core/playwright'
test('built UI investigates real saved evaluations, routes and commits guarded operator transitions',async({page},info)=>{
 test.setTimeout(90000);const file=process.env.ANOMALY_SURFACE_BROWSER_FIXTURE_FILE;if(!file)throw new Error('Use the owned live-host runner with BILLING_ANOMALY_BROWSER_SMOKE=1')
 const f=JSON.parse(await readFile(file,'utf8'));await page.addInitScript(f=>{const user={id:f.actorId,clientId:f.actorClientId,role:'Admin',email:f.email,displayName:'Development Testing',accessToken:f.accessToken,refreshToken:f.refreshToken,expiresIn:3600};localStorage.setItem('backoffice_access_token',f.accessToken);localStorage.setItem('backoffice_refresh_token',f.refreshToken);localStorage.setItem('backoffice-auth-persist',JSON.stringify({state:{accessToken:f.accessToken,refreshTokenValue:f.refreshToken,user},version:0}))},f)
 const path=`/billing/clients/${f.actorClientId}/reports/anomalies/${f.expenseId}`;await page.goto(path);const expense=page.getByRole('region',{name:'Expense anomaly signals',exact:true});await expect(expense.getByRole('heading',{name:'Investigation evidence'})).toBeVisible();await expect(expense.getByText(/Current operator status: open; revision 3/)).toBeVisible();await expect(expense.getByRole('link',{name:'Investigate with Development Testing Operations'})).toHaveAttribute('href',path);await expect(expense.getByText(/Breach observed/).last()).toBeVisible()
 await expense.getByRole('button',{name:'Acknowledge anomaly'}).focus();await page.keyboard.press('Enter');await page.getByRole('dialog').getByRole('button',{name:'Confirm operator status'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(expense.getByText(/Current operator status: acknowledged; revision 4/)).toBeVisible()
 await expense.getByRole('button',{name:'Resolve investigation'}).click();await page.getByRole('dialog').getByLabel('Operator reason (required)').fill('Development Testing investigated saved evidence');await page.getByRole('dialog').getByRole('button',{name:'Confirm operator status'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(expense.getByText(/Current operator status: resolved; revision 5/)).toBeVisible();await expense.getByRole('button',{name:'Reopen investigation'}).click();await page.getByRole('dialog').getByLabel('Operator reason (required)').fill('Development Testing reopens investigation');await page.getByRole('dialog').getByRole('button',{name:'Confirm operator status'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(expense.getByText(/Current operator status: open; revision 6/)).toBeVisible()
 await expense.getByRole('link',{name:'Investigate with Development Testing Operations'}).click();await page.reload();await expect(expense.getByText(/Current operator status: open; revision 6/)).toBeVisible();expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze()).violations).toEqual([])
 const creditPath=`/billing/clients/${f.actorClientId}/reports/anomalies/${f.creditId}`;await page.goto(creditPath.replace(f.actorClientId,f.actorClientId.toUpperCase()));await expect(page).toHaveURL(new RegExp(creditPath+'$'));const credit=page.getByRole('region',{name:'Abstract-credit consumption signals',exact:true});await expect(credit.getByText(/Current operator status: open; revision 0/)).toBeVisible()
 for(const [button,action,revision] of [['Acknowledge anomaly','acknowledged',1],['Resolve investigation','resolved',2],['Reopen investigation','open',3]] as const){await credit.getByRole('button',{name:button}).click();if(action!=='acknowledged')await page.getByRole('dialog').getByLabel('Operator reason (required)').fill('Development Testing credit investigation');await page.getByRole('dialog').getByRole('button',{name:'Confirm operator status'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(credit.getByText(new RegExp(`Current operator status: ${action}; revision ${revision}`))).toBeVisible()}
 await page.reload();await expect(credit.getByText(/Current operator status: open; revision 3/)).toBeVisible();expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze()).violations).toEqual([])
 await page.setViewportSize({width:320,height:700});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const storage=await page.evaluate(()=>JSON.stringify(Object.entries(localStorage)));expect(storage).not.toContain('Development Testing investigated saved evidence');expect(storage).not.toContain('configHash');expect(storage).not.toContain('effectiveExpense')
 await writeFile(info.outputPath('live-anomaly-summary.json'),JSON.stringify({pass:true,lane:'Built UI → actual Backoffice HTTP → PostgreSQL; evaluator-generated saved evidence; no HTTP mocks',operatorTransitions:6,expenseFinalRevision:6,creditFinalRevision:3,uppercaseClientRoutePreserved:true,ownerRouting:'Explicit Development Testing fixture, same authorized Client/evaluation',automatedAccessibility:true,responsive320:true,privateDraftPersistence:false,limits:'Hands-on screen reader, actual zoom and real-device acceptance remain open; no production approval'},null,2))
})
