import {test,expect} from '@playwright/test'
import {readFile,writeFile} from 'node:fs/promises'
interface Fixture {actorId:string;actorClientId:string;email:string;accessToken:string;refreshToken:string;oracles:{clientId:string;grants:string;consumption:string;postedConsumption:string;expenses:{currencyCode:string|null;observationCount:string;effectiveExpense:string|null;retainedEstimatedExpense:string|null}[]}[]}
test('built UI consumes real authorized Client-scoped HTTP reports and independent base-source totals',async({page},info)=>{
 test.setTimeout(60000)
 const fixtureFile=process.env.BILLING_REPORT_BROWSER_FIXTURE_FILE;if(!fixtureFile)throw new Error('Run the infrastructure-owned live-host runner with BILLING_REPORT_BROWSER_SMOKE=1')
 const fixture:Fixture=JSON.parse(await readFile(fixtureFile,'utf8'));const requests:{method:string;keys:string[];path:string}[]=[];let checks=0
 await page.addInitScript(f=>{const user={id:f.actorId,clientId:f.actorClientId,role:'Admin',email:f.email,displayName:'Report fixture',accessToken:f.accessToken,refreshToken:f.refreshToken,expiresIn:3600};localStorage.setItem('backoffice_access_token',f.accessToken);localStorage.setItem('backoffice_refresh_token',f.refreshToken);localStorage.setItem('backoffice-auth-persist',JSON.stringify({state:{accessToken:f.accessToken,refreshTokenValue:f.refreshToken,user},version:0}))},fixture)
 page.on('request',r=>{const url=new URL(r.url());if(url.pathname.startsWith('/api/billing/'))requests.push({method:r.method(),keys:[...url.searchParams.keys()].sort(),path:url.pathname})})
 for(const oracle of fixture.oracles){
  await page.goto(`/billing/clients/${oracle.clientId}/reports`);await expect(page.getByRole('heading',{name:'Full-window credit totals'})).toBeVisible();await page.getByLabel('From (inclusive UTC)').fill('2024-01-01T00:00:00Z');await page.getByLabel('To (exclusive UTC)').fill('2025-01-01T00:00:00Z');await page.getByLabel('UTC grain').selectOption('month');await page.getByRole('button',{name:'Apply filters'}).click()
  const credit=page.getByRole('region',{name:'Abstract-credit activity',exact:true}),expense=page.getByRole('region',{name:'Provider expense by currency',exact:true});await expect(credit).toHaveAttribute('aria-busy','false');await expect(expense).toHaveAttribute('aria-busy','false');const totals=credit.getByRole('table',{name:/Full-window abstract-credit totals/});const grouped=(v:string)=>{const [whole,fraction]=v.split('.');return whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')+'.'+fraction}
  for(const [label,value] of [['Grants',oracle.grants],['Consumption',oracle.consumption],['Posted consumption',oracle.postedConsumption]]){await expect(totals.getByRole('row').filter({has:page.getByRole('rowheader',{name:label,exact:true})})).toContainText(grouped(value));checks++}
  for(const expected of oracle.expenses){const label=expected.currencyCode??'Unknown currency';const card=expense.locator('.report-currency').filter({has:page.getByRole('heading',{name:label,exact:true})});await expect(card).toBeVisible();await expect(card.getByRole('row').filter({has:page.getByRole('rowheader',{name:'Effective expense (actual + unreconciled estimates)',exact:true})})).toContainText(expected.effectiveExpense===null?'Not available — unknown currency':`${expected.effectiveExpense} ${expected.currencyCode}`);await expect(card.getByRole('row').filter({has:page.getByRole('rowheader',{name:'Observations',exact:true})})).toContainText(expected.observationCount);checks+=2}
  if(await expense.getByRole('button',{name:'Load more',exact:true}).count()){const before=await expense.locator('.report-provenance').textContent();await expense.getByRole('button',{name:'Load more',exact:true}).click();await expect(expense).toHaveAttribute('aria-busy','false');expect(await expense.locator('.report-provenance').textContent()).toBe(before);checks++}
 }
 expect(requests.length).toBeGreaterThan(4);expect(requests.every(r=>r.method==='GET')).toBe(true);expect(requests.filter(r=>r.keys.includes('cursor')).every(r=>r.keys.join(',')==='clientId,cursor')).toBe(true)
 await writeFile(info.outputPath('live-smoke-summary.json'),JSON.stringify({result:'pass',lane:'built UI to real owned test API/PostgreSQL; no report HTTP mocks',clients:fixture.oracles.length,independentBaseSourceAssertions:checks,reportRequests:requests,privacy:'No token, body, amount, cursor value, invoice or provider payload recorded in this summary',limits:'Local isolated smoke; existing owned HTTP tests prove fresh authority and snapshot concurrency; manual accessibility and production profiles remain separate'},null,2))
})
